export interface LyricChunk {
  text: string;
  start: number;
  end: number;
}

export const LYRICS: LyricChunk[] = [
  { text: "Took a deep breath in the mirror", start: 6, end: 9 },
  { text: "He didn't like it when I wore high heels", start: 10, end: 12 },
  { text: "But I do", start: 12, end: 13 },
  { text: "Turn the lock and put my headphones on", start: 18, end: 20 },
  { text: "He always said he didn't get this song", start: 21, end: 24 },
  { text: "But I do,", start: 25, end: 26 },
  { text: "I do", start: 28, end: 29 },
  { text: "Walked in expecting you'd be late", start: 36, end: 38 },
  { text: "But you got here early and you stand and wave", start: 39, end: 41 },
  { text: "I walk to you", start: 42, end: 44 },
  { text: "You pull my chair out and help me in", start: 49, end: 51 },
  { text: "And you don't know how nice that is", start: 52, end: 54 },
  { text: "But I do", start: 55, end: 56 },
  { text: "And you throw your head back laughing", start: 60, end: 62 },
  { text: "Like a little kid", start: 63, end: 65 },
  { text: "I think it's strange that you think I'm funny, 'cause", start: 67, end: 69 },
  { text: "He never did", start: 70, end: 72 },
  { text: "I've been spending the last eight months", start: 73, end: 75 },
  { text: "Thinking all love ever does", start: 76, end: 78 },
  { text: "Is break and burn, and end", start: 79, end: 83 },
  { text: "But on a Wednesday in a cafe", start: 85, end: 88 },
  { text: "I watched it begin again", start: 89, end: 91 },
  { text: "You said you never met one girl who had", start: 97, end: 99 },
  { text: "As many James Taylor records as you", start: 100, end: 103 },
  { text: "But I do", start: 103, end: 105 },
  { text: "We tell stories and you don't know why", start: 109, end: 112 },
  { text: "I'm coming off a little shy", start: 113, end: 115 },
  { text: "But I do", start: 115, end: 117 },
  { text: "But you throw your head back laughing", start: 121, end: 124 },
  { text: "Like a little kid", start: 125, end: 127 },
  { text: "I think it's strange that you think I'm funny, 'cause", start: 128, end: 130 },
  { text: "He never did", start: 131, end: 133 },
  { text: "I've been spending the last eight months", start: 134, end: 135 },
  { text: "Thinking all love ever does", start: 136, end: 138 },
  { text: "Is break and burn, and end", start: 139, end: 144 },
  { text: "But on a Wednesday in a cafe", start: 146, end: 149 },
  { text: "I watched it begin again", start: 150, end: 152 },
  { text: "And we walked down the block, to my car", start: 163, end: 166 },
  { text: "And I almost brought him up", start: 167, end: 169 },
  { text: "But you start to talk about the movies", start: 170, end: 173 },
  { text: "That your family watches", start: 174, end: 176 },
  { text: "every single Christmas", start: 177, end: 178 },
  { text: "And I want to talk about that", start: 179, end: 181 },
  { text: "And for the first time", start: 182, end: 183 },
  { text: "What's past is past", start: 184, end: 187 },
  { text: "'Cause you throw your head back laughing", start: 191, end: 194 },
  { text: "Like a little kid", start: 195, end: 196 },
  { text: "I think it's strange that you think I'm funny, 'cause", start: 197, end: 200 },
  { text: "He never did", start: 201, end: 202 },
  { text: "I've been spending the last eight months", start: 203, end: 206 },
  { text: "Thinking all love ever does", start: 207, end: 209 },
  { text: "Is break and burn, and end", start: 210, end: 214 },
  { text: "But on a Wednesday in a cafe", start: 216, end: 219 },
  { text: "I watched it begin again", start: 220, end: 223 },
  { text: "But on a Wednesday in a cafe", start: 228, end: 230 },
  { text: "I watched it begin again", start: 231, end: 234 },
];

export enum RoseStage {
  SEED = "seed",
  GERMINATION = "germination",
  SPROUT = "sprout",
  LEAVES = "leaves",
  YOUNG_PLANT = "young_plant",
  BUD = "bud",
  BLOOMING = "blooming",
  FULL_BLOOM = "full_bloom",
}

export const ROSE_STAGES = [
  { stage: RoseStage.SEED, start: 0 },
  { stage: RoseStage.GERMINATION, start: 12 },
  { stage: RoseStage.SPROUT, start: 22 },
  { stage: RoseStage.LEAVES, start: 36 },
  { stage: RoseStage.YOUNG_PLANT, start: 49 },
  { stage: RoseStage.BUD, start: 96 },
  { stage: RoseStage.BLOOMING, start: 158 },
  { stage: RoseStage.FULL_BLOOM, start: 212 },
];
